// Integration test (CI-proxy, CPU-only): load a tiny Mixtral-style MoE GGUF
// with STRATAFLOW_FORCE_STREAM_EXPERTS=1 so the routed-expert FFN tensors are
// owned by strata_stream_buft, then assert the model loads, decodes a valid
// token, and the buffer type recorded >=1 expert registration.
//
// The fixture is generated by tools/testdata/make_tiny_moe_gguf.py. This test
// is GUARDED on STRATAFLOW_TEST_MOE_GGUF pointing at that fixture, mirroring
// the existing test_model_load STRATAFLOW_TEST_GGUF pattern, so the suite stays
// green in environments where the fixture is not generated. Generate + run:
//     uv run --with gguf --with numpy python3
//         tools/testdata/make_tiny_moe_gguf.py /path/tiny_moe.gguf
//     STRATAFLOW_TEST_MOE_GGUF=/path/tiny_moe.gguf ctest -R test_moe_stream
// Copyright 2026 Coaade Inc. SPDX-License-Identifier: LicenseRef-Coaade-Source-Available-1.0
#include "hw/profiler.h"
#include "model/model.h"
#include "plan/planner.h"
#include "test_util.h"
#include "tws/stream_buft.h"

#include <cstdlib>
#include <memory>
#include <string>

using namespace sf;

static HardwareProfile cpu_profile() {
    HardwareProfile hw;
    hw.ram_total_bytes = 32ull * 1024 * 1024 * 1024;
    hw.ram_free_bytes = 28ull * 1024 * 1024 * 1024;
    return hw;
}

// Portable setenv for the force-stream switch.
static void set_force_stream(bool on) {
#if defined(_WIN32)
    _putenv_s("STRATAFLOW_FORCE_STREAM_EXPERTS", on ? "1" : "");
#else
    if (on) setenv("STRATAFLOW_FORCE_STREAM_EXPERTS", "1", 1);
    else    unsetenv("STRATAFLOW_FORCE_STREAM_EXPERTS");
#endif
}

static void test_moe_streams_through_buft() {
    const char *path = std::getenv("STRATAFLOW_TEST_MOE_GGUF");
    if (path == nullptr || path[0] == '\0') {
        std::printf("[skipped: set STRATAFLOW_TEST_MOE_GGUF] ");
        return;
    }

    reset_stream_buft_stats();
    set_force_stream(true);

    std::unique_ptr<Model> m;
    PlacementPlan plan;
    CHECK_EQ(load_model(path, cpu_profile(), 0, 0, m, &plan), SF_OK);
    CHECK(m != nullptr);

    // The fixture is a real MoE model (expert_count > 1).
    CHECK(m->shape().is_moe);
    CHECK(m->shape().n_experts > 1u);
    CHECK(m->shape().n_layers > 0u);

    // The forced-streaming path must have routed the stacked expert FFN tensors
    // through strata_stream_buft: at least one buffer allocated and at least one
    // expert tensor registered (3 per layer: gate/down/up).
    const StreamBuftStats &s = stream_buft_stats();
    CHECK(s.buffers >= 1u);
    CHECK(s.registrations >= 1u);
    CHECK(s.stored_bytes > 0u);

    // Decode a token: the CPU MoE kernel must read valid, resident expert bytes
    // from the streaming buffer and produce an in-vocabulary token id.
    auto ids = m->tokenize("hello world");
    CHECK(!ids.empty());
    int32_t next = m->forward(ids.back());
    CHECK(next >= 0);

    set_force_stream(false);
}

static void run_all() {
    RUN(test_moe_streams_through_buft);
}

TEST_MAIN()
